apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoind.fullname" . }}
  labels:
    {{- include "bitcoind.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.config.rpc.port }}
      targetPort: {{ .Values.config.rpc.port }}
      protocol: TCP
      name: rpc
    - port: {{ .Values.config.zmqblock.port }}
      targetPort: {{ .Values.config.zmqblock.port }}
      protocol: TCP
      name: zmqblock
    - port: {{ .Values.config.zmqtx.port }}
      targetPort: {{ .Values.config.zmqtx.port }}
      protocol: TCP
      name: zmqtx      
  selector:
    {{- include "bitcoind.selectorLabels" . | nindent 4 }}